### ISSUE TITLE
Panic error decoding .HEIC file

### ISSUE THREAD

**Issue by jamesriady** [gen2brain/heic#6] opened 2024-09-10 07:01 UTC
**Issue**: Encountered a panic error while decoding a .HEIC document with a size of 1.6MB.

### Steps to Reproduce:

1. Attempt to decode a .HEIC file of 1.6MB using the lib.
2. Observe the panic error.
<img width="958" alt="Screenshot 2024-09-10 at 2 00 35 PM" src="https://github.com/user-attachments/assets/35079857-f142-4caf-9b69-678b5c13bc14">

### Expected Behavior:
The library should successfully decode the .HEIC document without errors.

### Additional Notes:

- Decoding .HEIF files from the library's testdata directory works as expected.
- go version go1.23.0 darwin/arm64

**Comment by gen2brain** [comment] 2024-09-10 08:15
Can you upload the image? I cannot reproduce it without it.

**Comment by jamesriady** [comment] 2024-09-10 09:03
here is the image @gen2brain 

[IMG_0928.HEIC.zip](https://github.com/user-attachments/files/16942312/IMG_0928.HEIC.zip)

**Comment by gen2brain** [comment] 2024-09-10 09:17
Thanks, I can reproduce it. I see there is a new version of libheif with a lot of fixes, will try to update it when I find the time.

**Comment by gen2brain** [comment] 2024-10-31 13:40
This is fixed in https://github.com/gen2brain/heic/commit/57be0564ff4e0c71539b70edf5bf69520f2128ab.

**Closed as completed by gen2brain** 2024-10-31 13:40 UTC
