### ISSUE TITLE
"image: unknown format" in decoding image

### ISSUE THREAD

**Issue by storybehind** [gen2brain/heic#2] opened 2024-04-03 14:07 UTC
After importing this library, decoding `.heic` file using standard image package produces `image: unknown format` error. 

`heic.Dynamic()` prints `cannot load library: libheif.so: cannot open shared object file: No such file or directory` as this library is not installed on my machine. But, it's not falling back to WASM.

**Comment by gen2brain** [comment] 2024-04-03 14:12
It does fallback, but it cannot detect the image probably because the image doesn't start with `????ftypheic`, can you check the header of the file?

**Comment by storybehind** [comment] 2024-04-03 16:47
<img width="659" alt="invalid-magic-number-heic" src="https://github.com/gen2brain/heic/assets/25722614/3ef14d20-01d5-4ae4-8482-e8a2f5c35f5e">


The image starts like above. Some other `heic` files have same magic number as you commented above. I'm not sure of the reason for this difference. Just found a [discussion ](https://github.com/strukturag/libheif/issues/83) on `heic` magic number.

**Comment by gen2brain** [comment] 2024-04-03 17:06
Yeah, I know that discussion, but nothing is confirmed there, `ftypmif1` can be used for both AVIF and HEIF. As for `libheif`, it also can handle AVIF and JPEG in HEIF, etc. This library only uses HEIC, i.e. HEVC in HEIF, I need to know if that is H.265 encoded or not.
You can help with testing, i.e. try to add another line below, same as https://github.com/gen2brain/heic/blob/main/heic.go#L63 just with `ftypmif1` instead of `ftypheic` and use `replace` directive in go.mod so you can test with your version. If it works I can include it here in the repo, but I am still not sure how to be precise here and if it would be correct.

**Comment by gen2brain** [comment] 2024-04-05 07:58
If possible, please send me an image via email so I can test it.

**Comment by storybehind** [comment] 2024-04-08 09:45
Attached requested image.

**Comment by gen2brain** [comment] 2024-04-08 12:46
Sorry, I do not see it attached. You can also send directly to private email if you want.

**Comment by gen2brain** [comment] 2024-10-31 13:42
I am closing this one. If you can send me an image that would be nice, feel free to open a new issue.

**Closed as completed by gen2brain** 2024-10-31 13:42 UTC
